// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"todo_app/internal/configs"
	"todo_app/internal/externalinterface/server"
)

// Injectors from wire.go:

func InitializeServer(configConfig *config.Config) server.Server {
	serverServer := server.NewServer(configConfig)
	return serverServer
}
